# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cpp function to obtain
#'   estimated regression coefficients
#'   standard errors of the estimates
#'   95% confidence interval of each coefficient
#'   predicted values
#'   residuals
#' 
#' @param x predictor, n by 1 numeric vector
#' @param y response, n by 1 numeric vector
#' @param n number of observations, integer
#' @param sig_level significance level of the confidence interval, double
#' @return result of fit List
#' @export
SimpLinCpp <- function(x, y, n, sig_level) {
    .Call(`_SimpLin_SimpLinCpp`, x, y, n, sig_level)
}

rcpparma_hello_world <- function() {
    .Call(`_SimpLin_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_SimpLin_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_SimpLin_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_SimpLin_rcpparma_bothproducts`, x)
}

